CREATE USER "vagrant" WITH PASSWORD 'vagrant';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "vagrant";
GRANT USAGE ON SCHEMA public TO "vagrant";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "vagrant";
